name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    
    # This GitHub Action installs a Rust toolchain using rustup. It is designed for one-line concise usage and good defaults.
    # It also takes care of caching intermediate build artifacts.
    - name: Install the Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    steps:
      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build

      runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  format:
    - name: Format
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          components: clippy rustfmt
      - name: clippy
        run: cargo clippy -- -D warnings
      - name: fmt
        run: cargo fmt -- --check

  coverage:
    - name: Coverage
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov.info
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Generate report
        run: cargo llvm-cov report --html --output-dir coverage
      - uses: actions/upload-artifact@v4
        with:
          name: "Coverage report"
          path: coverage/
